name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Set up database.yml for CI
        run: |
          echo "default: &default
            adapter: mysql2
            encoding: utf8mb4
            pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
            username: root
            password:
            host: 127.0.0.1
            port: 3306
          
          test:
            <<: *default
            database: todo_app_test" > backend/config/database.yml

      - name: Setup database
        env:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
        run: |
          cd backend
          bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
        run: |
          cd backend
          bundle exec rspec

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: todo_app_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up database.yml for CI
        run: |
          echo "default: &default
            adapter: mysql2
            encoding: utf8mb4
            pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
            username: root
            password: rootpassword
            host: 127.0.0.1
            port: 3306
          
          test:
            <<: *default
            database: todo_app_test" > backend/config/database.yml

      - name: Setup database
        env:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
        run: |
          cd backend
          bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
        run: |
          cd backend
          bundle exec rspec